"family_title": "👨‍👩‍👧‍👦 ALADDIN Family",
"family_protection_title": "FAMILY PROTECTION",
"family_protection_accessibility": "Family protection",
"family_members": "Members",
"family_members_title": "FAMILY MEMBERS",
"family_add_member": "Add member",
"family_add_member_title": "Add member",
"family_add_first_member": "➕ Add first member",
"family_no_members": "No family members",
"family_parental_control": "PARENTAL CONTROL",
"family_settings": "Settings",
"family_gamification": "GAMIFICATION",
"family_child_reward": "Child reward",
"family_rewards_modal_title": "🦄 Child reward",
"family_unicorn_balance_format": "%d unicorns available",
"family_add_more_member": "Add more",
"add_member_title": "Add member",
"add_member_subtitle": "Choose a convenient way to invite a new user",
"add_member_create_family": "Create a new family",
"add_member_create_family_desc": "Fill out the family profile and invite relatives from scratch",
"add_member_scan_qr": "Scan QR",
"add_member_scan_qr_desc": "Open the camera and scan the invitation code",
"add_member_enter_code": "Enter code manually",
"add_member_enter_code_desc": "Enter or paste the invitation code from the administrator",
"add_member_privacy_title": "Your data is protected",
"add_member_privacy_text": "All invitations are encrypted and never shared with third parties. Access can be revoked at any time.",
"add_member_cancel": "Cancel",
"family_contacts_total": "Total contacts",
"family_messages_title": "Messages",
"family_messages_format": "%d messages",
"family_calls_format": "%d calls",
"family_last_contact_prefix": "Last contact:",
"family_blocked_sites": "Blocked sites",
"family_blocked_apps": "Blocked apps",
"family_statistics_week": "📊 Statistics for the week:",
"family_apps": "apps",
"family_contacts": "Contacts",
"family_statistics_today": "Statistics today",
"family_statistics_today_detailed": "Detailed statistics for today",
"family_statistics_week_detailed": "Detailed statistics for the week",
"family_instagram": "Instagram",
"family_top_site": "Top site:",
"family_top_5_sites": "Top 5 sites for the week",
"family_top_app": "Top app:",
"family_top_5_apps": "Top 5 apps for the week",
"family_visits": "visits",
"family_total_time": "Total time",
"family_suspicious_activity": "Suspicious activity",
"family_tiktok": "TikTok:",
"family_unlock": "Unlock",
"family_active": "active",
"family_access_requests": "Access requests",
"family_dangerous_queries": "Dangerous queries",
"payment_qr_error_payment_failed": "Платёж не был выполнен. Попробуйте создать новый платёж.",
"payment_qr_success_message": "Subscription %@ activated!\n\nThank you for your purchase!",
"payment_qr_error_title": "Error",
"payment_qr_error_ok": "OK",
"payment_qr_loading": "Loading QR code...",
"payment_qr_creating": "Creating payment...",
"payment_qr_error_load": "Unable to load the QR code.",
"payment_qr_error_connection": "Check your internet connection and try again.",
"payment_qr_timer_until": "until payment expires",
"payment_qr_error_network_format": "Проблема с подключением к интернету.\n\n%@\n\nПроверьте соединение и попробуйте снова.",
"payment_qr_error_empty_qr": "Failed to obtain QR code. The server returned an empty response. Please try again or contact support.",
"payment_qr_error_qr_pending": "QR code is still loading. Please wait a few seconds and try again.",
