#!/bin/bash
# 🚀 Скрипт для ручного деплоя через веб-интерфейс или SSH

echo "=========================================="
echo "🚀 ИНСТРУКЦИЯ ПО ДЕПЛОЮ ИСПРАВЛЕНИЯ"
echo "=========================================="
echo ""
echo "📋 ФАЙЛ ДЛЯ ОБНОВЛЕНИЯ:"
echo "   Локальный: app/auth/auth.py"
echo "   Серверный: /opt/aladdin-backend/app/auth/auth.py"
echo ""
echo "🔧 ВАРИАНТЫ ДЕПЛОЯ:"
echo ""
echo "1️⃣ ЧЕРЕЗ SSH (если доступен):"
echo "   ssh root@149.154.65.180"
echo "   cd /opt/aladdin-backend/app/auth"
echo "   cp auth.py auth.py.backup_\$(date +%Y%m%d_%H%M%S)"
echo "   # Загрузить файл через scp или sftp"
echo "   python3 -m py_compile auth.py"
echo "   systemctl restart aladdin-backend"
echo ""
echo "2️⃣ ЧЕРЕЗ SCP (с локальной машины):"
echo "   scp app/auth/auth.py root@149.154.65.180:/opt/aladdin-backend/app/auth/auth.py"
echo "   ssh root@149.154.65.180 'systemctl restart aladdin-backend'"
echo ""
echo "3️⃣ ЧЕРЕЗ ВЕБ-ИНТЕРФЕЙС:"
echo "   - Войти в панель управления сервером"
echo "   - Перейти в файловый менеджер"
echo "   - Загрузить app/auth/auth.py в /opt/aladdin-backend/app/auth/"
echo "   - Перезапустить через терминал: systemctl restart aladdin-backend"
echo ""
echo "🧪 ПРОВЕРКА ПОСЛЕ ДЕПЛОЯ:"
echo "   curl -k https://aladdin-ai.ru/api/health"
echo "   curl -H 'Authorization: Bearer TOKEN' https://aladdin-ai.ru/api/family/stats"
echo ""
echo "📝 ПОДРОБНЫЕ ИНСТРУКЦИИ:"
echo "   См. docs/ДЕПЛОЙ_ЧЕРЕЗ_NGINX_SSL_SYSTEMD.md"
echo ""
