#!/bin/bash
# Быстрое развертывание - выполните: bash quick_deploy.sh

SERVER="root@149.154.65.180"
REMOTE="/opt/aladdin-backend"
LOCAL="/Users/sergejhlystov/ALADDIN_NEW/ALADDIN_NEW/mobile_apps/ALADDIN_iOS"

echo "🚀 Быстрое развертывание ALADDIN API Gateway"
echo ""
echo "Выполните следующие команды вручную:"
echo ""
echo "1. Загрузка файлов:"
echo "   scp $LOCAL/api_gateway_complete.py $SERVER:$REMOTE/"
echo "   scp $LOCAL/sfm_adapter.py $SERVER:$REMOTE/"
echo ""
echo "2. Подключение и развертывание:"
echo "   ssh $SERVER"
echo "   cd $REMOTE"
echo "   cp api_gateway.py api_gateway_backup_\$(date +%Y%m%d_%H%M%S).py"
echo "   python3 -m py_compile api_gateway_complete.py"
echo "   cp api_gateway_complete.py api_gateway.py"
echo "   systemctl restart aladdin-api-gateway || systemctl restart aladdin-main-api-gateway"
echo "   sleep 10"
echo "   curl http://127.0.0.1:8002/api/health"
echo ""
echo "Или используйте готовые скрипты:"
echo "   ./deploy_api_gateway_final.exp"
echo "   или"
echo "   ./deploy_now.sh"
