#!/bin/bash
# Ручная загрузка файлов Варианта 5 на сервер (без sshpass)

SERVER_IP="149.154.65.180"
SERVER_USER="root"
SERVER_PATH="/opt/aladdin-backend"

echo "🚀 ИНСТРУКЦИЯ ПО ЗАГРУЗКЕ ВАРИАНТА 5 НА СЕРВЕР"
echo "=============================================="
echo ""
echo "Выполните следующие команды вручную:"
echo ""
echo "1. Загрузка Reports Router:"
echo "   scp security/api/routers/reports_router.py root@$SERVER_IP:$SERVER_PATH/security/api/routers/"
echo ""
echo "2. Загрузка Analytics Router (обновленный):"
echo "   scp app/routers/analytics_router.py root@$SERVER_IP:$SERVER_PATH/app/routers/"
echo ""
echo "3. Загрузка Main.py (обновленный):"
echo "   scp main.py root@$SERVER_IP:$SERVER_PATH/"
echo ""
echo "4. Подключение к серверу:"
echo "   ssh root@$SERVER_IP"
echo ""
echo "5. На сервере - проверка синтаксиса:"
echo "   cd $SERVER_PATH"
echo "   python3 -m py_compile security/api/routers/reports_router.py"
echo "   python3 -m py_compile app/routers/analytics_router.py"
echo "   python3 -m py_compile main.py"
echo ""
echo "6. Перезапуск сервиса:"
echo "   systemctl restart aladdin-main-api-gateway"
echo ""
echo "7. Проверка статуса:"
echo "   systemctl status aladdin-main-api-gateway"
echo ""
echo "8. Проверка health:"
echo "   curl -s http://127.0.0.1:8002/api/health"
echo ""
echo "9. Проверка логов:"
echo "   journalctl -u aladdin-main-api-gateway -n 50 | grep -E '(Reports|Analytics|WILDCARD)'"
echo ""
