api_timeout_seconds: 10
batch_size: 100
block_duration_minutes: 60
cache_enabled: true
cache_ttl_seconds: 3600
child_protection_mode: true
critical_threshold: 0.9
debug_mode: true
elderly_protection_mode: true
enable_api_integration: true
enable_notifications: true
enable_webhook_notifications: false
enabled: true
family_protection_enabled: true
log_audit_events: true
log_level: DEBUG
log_performance_events: true
log_security_events: true
max_attempts_per_hour: 150
max_cache_size: 10000
max_concurrent_operations: 10
notification_email: null
notification_sms: null
suspicious_threshold: 0.7
timeout_seconds: 30
version: '2.5'
webhook_url: null
