#!/usr/bin/env python3
"""Generate Core/Planning/PlanItem275CatalogMirror.generated.swift from the 275 matrix.

Re-run after editing docs/PLAN_ITEM_TRACEABILITY_MATRIX_FULL.md:
  python3 scripts/generate_plan_item_275_mirror.py
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
MATRIX = ROOT / "docs" / "PLAN_ITEM_TRACEABILITY_MATRIX_FULL.md"
OUT = ROOT / "Core" / "Planning" / "PlanItem275CatalogMirror.generated.swift"

ROW_RE = re.compile(r"^- (.+)$")


def parse_rows(text: str) -> list[list[str]]:
    rows: list[list[str]] = []
    for line in text.splitlines():
        m = ROW_RE.match(line.strip())
        if not m:
            continue
        body = m.group(1)
        if "|" not in body:
            continue
        parts = [p.strip() for p in body.split("|")]
        if len(parts) != 8:
            continue
        rows.append(parts)
    return rows


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").replace("\r", "")


def status_enum_case(status: str) -> str:
    if status == "DONE":
        return "done"
    if status == "PARTIAL":
        return "partial"
    if status == "TODO":
        return "todo"
    raise ValueError(f"bad status: {status}")


def main() -> int:
    if not MATRIX.exists():
        print("FAIL: matrix not found", file=sys.stderr)
        return 1
    rows = parse_rows(MATRIX.read_text(encoding="utf-8"))
    if not rows:
        print("FAIL: no rows", file=sys.stderr)
        return 1
    for r in rows:
        if r[3] not in {"DONE", "PARTIAL", "TODO"}:
            print("FAIL: invalid status", r, file=sys.stderr)
            return 1

    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = [
        "// AUTO-GENERATED by scripts/generate_plan_item_275_mirror.py — do not edit by hand.",
        f"// Re-run: python3 scripts/generate_plan_item_275_mirror.py",
        f"// Source: docs/PLAN_ITEM_TRACEABILITY_MATRIX_FULL.md",
        f"// Generated at (UTC): {now}",
        "",
        "import Foundation",
        "",
        "enum PlanItem275Status: String, Hashable, Codable {",
        "    case done = \"DONE\"",
        "    case partial = \"PARTIAL\"",
        "    case todo = \"TODO\"",
        "}",
        "",
        "struct PlanItem275CatalogLine: Identifiable, Hashable {",
        "    let id: String",
        "    let planTitle: String",
        "    let categoryId: String",
        "    let itemId: String",
        "    let status: PlanItem275Status",
        "    let owner: String",
        "    let due: String",
        "    let gates: String",
        "    let wave: String",
        "}",
        "",
        "enum PlanItem275CatalogMirror {",
        f"    static let generatedAtUTC: String = \"{now}\"",
        f"    static let rowCount: Int = {len(rows)}",
        "",
        "    static let allLines: [PlanItem275CatalogLine] = [",
    ]

    for r in rows:
        plan_title, cat, item_id, status, owner, due, gates, wave = r
        line_id = f"{esc(cat)}|{esc(item_id)}"
        se = status_enum_case(status)
        lines.append(
            "        .init("
            f'id: "{line_id}", '
            f'planTitle: "{esc(plan_title)}", '
            f'categoryId: "{esc(cat)}", '
            f'itemId: "{esc(item_id)}", '
            f"status: .{se}, "
            f'owner: "{esc(owner)}", '
            f'due: "{esc(due)}", '
            f'gates: "{esc(gates)}", '
            f'wave: "{esc(wave)}"'
            "),"
        )

    done_n = sum(1 for r in rows if r[3] == "DONE")
    partial_n = sum(1 for r in rows if r[3] == "PARTIAL")
    todo_n = sum(1 for r in rows if r[3] == "TODO")

    lines.append("    ]")
    lines.append("")
    lines.append(f"    static let doneCount: Int = {done_n}")
    lines.append(f"    static let partialCount: Int = {partial_n}")
    lines.append(f"    static let todoCount: Int = {todo_n}")
    lines.append("")
    lines.append("    static var openLines: [PlanItem275CatalogLine] {")
    lines.append("        allLines.filter { $0.status == .partial || $0.status == .todo }")
    lines.append("    }")
    lines.append("")
    lines.append("    static var doneOnlyLines: [PlanItem275CatalogLine] {")
    lines.append("        allLines.filter { $0.status == .done }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"OK: wrote {OUT.relative_to(ROOT)} lines={len(rows)} DONE={done_n} PARTIAL={partial_n} TODO={todo_n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
