name: iOS Release Build

on:
  push:
    tags:
      - 'v*'
    paths: [ 'mobile_apps/ALADDIN_iOS/**' ]

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
        
    - name: Cache Swift packages
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
          ~/Library/Caches/CocoaPods
        key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-
          
    - name: Install dependencies
      run: |
        cd mobile_apps/ALADDIN_iOS
        if [ -f Podfile ]; then
          pod install
        fi
        
    - name: Build for release
      run: |
        cd mobile_apps/ALADDIN_iOS
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -configuration Release -destination 'generic/platform=iOS' build
        
    - name: Archive for App Store
      run: |
        cd mobile_apps/ALADDIN_iOS
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -configuration Release -destination 'generic/platform=iOS' archive -archivePath ALADDIN.xcarchive
        
    - name: Export IPA
      run: |
        cd mobile_apps/ALADDIN_iOS
        xcodebuild -exportArchive -archivePath ALADDIN.xcarchive -exportPath ./build -exportOptionsPlist ExportOptions.plist
        
    - name: Upload IPA to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: ALADDIN-iOS-${{ github.ref_name }}
        path: mobile_apps/ALADDIN_iOS/build/ALADDIN.ipa
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ALADDIN iOS ${{ github.ref_name }}
        body: |
          ALADDIN Family iOS App Release ${{ github.ref_name }}
          
          ## Changes
          - iOS app build
          - Ready for App Store submission
          
          ## Download
          Download the IPA file from the artifacts section.
        draft: false
        prerelease: false
