name: Auto Format Code

on:
  workflow_dispatch:  # Ручной запуск
  schedule:
    # Запуск каждую неделю в воскресенье в 3:00 UTC
    - cron: '0 3 * * 0'

jobs:
  auto-format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    
    - name: Install formatting tools
      run: |
        python -m pip install --upgrade pip
        pip install black autopep8 isort pre-commit
    
    - name: Run auto formatter
      run: |
        python3 scripts/auto_format_all.py
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto-format code with black, autopep8, and isort"
        git push