name: iOS Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: Verify project structure
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "=== ПРОВЕРЯЕМ СТРУКТУРУ ПРОЕКТА ==="
        ls -la
        echo ""
        echo "=== ПРОВЕРЯЕМ XCODE ПРОЕКТ ==="
        ls -la ALADDIN.xcodeproj/
        echo ""
        echo "=== ПРОВЕРЯЕМ СХЕМУ ==="
        ls -la ALADDIN.xcodeproj/xcshareddata/xcschemes/
        echo ""
        echo "=== ПРОВЕРЯЕМ ASSETS ==="
        ls -la ALADDIN/Assets.xcassets/AppIcon.appiconset/
        
    - name: List available simulators
      run: |
        xcrun simctl list devices available
        
    - name: Build iOS app
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "=== КОМПИЛИРУЕМ iOS ПРИЛОЖЕНИЕ ==="
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination 'generic/platform=iOS Simulator' build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: ios-build
        path: mobile_apps/ALADDIN_iOS/build/Release-iphonesimulator/

