name: iOS Minimal Test - Basic Check

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/minimal_test.txt' ]

jobs:
  minimal-test:
    runs-on: macos-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Minimal Test - Basic Check
      run: |
        echo "🔍 МИНИМАЛЬНЫЙ ТЕСТ - БАЗОВАЯ ПРОВЕРКА"
        echo "====================================="
        
        echo "1️⃣ ПРОВЕРЯЕМ НАЛИЧИЕ XCODE:"
        which xcodebuild || echo "xcodebuild не найден"
        xcodebuild -version || echo "xcodebuild не работает"
        
        echo ""
        echo "2️⃣ ПРОВЕРЯЕМ НАЛИЧИЕ СИМУЛЯТОРОВ:"
        which xcrun || echo "xcrun не найден"
        xcrun simctl list devices | head -10 || echo "simctl не работает"
        
        echo ""
        echo "3️⃣ ИЩЕМ ЛЮБЫЕ iOS ПРОЕКТЫ:"
        find . -name "*.xcodeproj" -type d | head -5
        find . -name "*.xcworkspace" -type d | head -5
        
        echo ""
        echo "4️⃣ ПРОВЕРЯЕМ SDK:"
        xcodebuild -showsdks | grep -i ios | head -5 || echo "iOS SDK не найдены"
        
        echo ""
        echo "5️⃣ ПРОСТАЯ ПРОВЕРКА КОМПИЛЯЦИИ:"
        if find . -name "*.xcodeproj" -type d | head -1 | read project; then
          echo "Найден проект: $project"
          cd "$(dirname "$project")"
          echo "Пробуем компилировать:"
          xcodebuild -project "$(basename "$project")" -list || echo "Не удалось получить список схем"
        else
          echo "❌ НИ ОДНОГО .xcodeproj ФАЙЛА НЕ НАЙДЕНО!"
        fi
        
    - name: Upload Minimal Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-minimal-test
        path: .
        retention-days: 1
