name: iOS Solution 2 - Create Simulator

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/trigger_solution2.txt' ]

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: Create and boot simulator
      run: |
        echo "=== СОЗДАЕМ НОВЫЙ СИМУЛЯТОР ==="
        
        # Получаем доступные типы устройств
        DEVICE_TYPE=$(xcrun simctl list devicetypes | grep iPhone | head -1 | awk -F'[()]' '{print $2}')
        echo "Тип устройства: $DEVICE_TYPE"
        
        # Получаем доступные runtime
        RUNTIME=$(xcrun simctl list runtimes | grep iOS | head -1 | awk -F'[()]' '{print $2}')
        echo "Runtime: $RUNTIME"
        
        # Создаем симулятор
        SIMULATOR_ID=$(xcrun simctl create "iPhone Test" "$DEVICE_TYPE" "$RUNTIME")
        echo "Создан симулятор: $SIMULATOR_ID"
        echo "simulator_id=$SIMULATOR_ID" >> $GITHUB_ENV
        
        # Запускаем симулятор
        xcrun simctl boot "$SIMULATOR_ID"
        echo "Симулятор запущен"
        
    - name: Build on created simulator
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "=== КОМПИЛИРУЕМ НА СОЗДАННОМ СИМУЛЯТОРЕ ==="
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination "generic/platform=iOS Simulator" build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-build-solution2
        path: mobile_apps/ALADDIN_iOS/build/
        retention-days: 7