name: iOS Final Test 4 - Asset Catalog Bypass
on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/final_test4.txt' ]
  workflow_dispatch:

jobs:
  asset-catalog-bypass:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
    
    - name: Run Asset Catalog Bypass Build
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "🎯 ТЕСТ 4: ASSET CATALOG ОБХОД"
        echo "============================="
        echo ""
        echo "🔍 ПРОБЛЕМА:"
        echo "❌ CompileAssetCatalog падает из-за runtime несовместимости"
        echo "❌ Asset catalog требует совместимые версии"
        echo ""
        echo "✅ РЕШЕНИЕ:"
        echo "1. Полностью отключаем asset catalog"
        echo "2. Отключаем все asset операции"
        echo "3. Используем минимальные настройки"
        echo ""
        
        echo "🧪 ТЕСТ: Asset catalog обход"
        if xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator" \
          IPHONEOS_DEPLOYMENT_TARGET=13.0 \
          CODE_SIGNING_ALLOWED=NO \
          ASSETCATALOG_COMPILER_APPICON_NAME="" \
          ASSETCATALOG_COMPILER_ACCENT_COLOR_NAME="" \
          COMPILER_INDEX_STORE_ENABLE=NO \
          build; then
          
          echo "✅ УСПЕХ! Asset catalog обход работает!"
          
          echo ""
          echo "📱 Результат сборки:"
          ls -la build/ || echo "build папка не найдена"
          echo ""
          echo "📱 Ищем .app файлы:"
          find build/ -name "*.app" -type d || echo ".app файлы не найдены"
          
          echo ""
          echo "🎉 РЕШЕНИЕ НАЙДЕНО!"
          echo "Команда: ASSETCATALOG_COMPILER_APPICON_NAME='' + ASSETCATALOG_COMPILER_ACCENT_COLOR_NAME=''"
          
        else
          echo "❌ Asset catalog обход не работает"
          echo "Пробуем без asset catalog вообще:"
          if xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator" \
            IPHONEOS_DEPLOYMENT_TARGET=13.0 \
            CODE_SIGNING_ALLOWED=NO \
            build; then
            echo "✅ УСПЕХ! Без asset catalog работает!"
          else
            echo "❌ Без asset catalog тоже не работает"
          fi
        fi
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: ios-asset-catalog-bypass
        path: mobile_apps/ALADDIN_iOS/build/
        if-no-files-found: warn
