name: iOS Final Correct Test

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/trigger_final_correct.txt' ]

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: List available simulators
      run: |
        echo "=== ДОСТУПНЫЕ СИМУЛЯТОРЫ ==="
        xcrun simctl list devices available | grep iPhone
        
    - name: Final Correct Test
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "=== ФИНАЛЬНЫЙ ПРАВИЛЬНЫЙ ТЕСТ ==="
        echo "Используем platform=iOS Simulator (НЕ platform=iOS!)"
        echo "GitHub Actions имеет симуляторы, но НЕ имеет реальных iPhone"
        
        # Пробуем разные варианты
        echo ""
        echo "1. platform=iOS Simulator (без имени):"
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination "platform=iOS Simulator" build || echo "Вариант 1 не сработал"
        
        echo ""
        echo "2. platform=iOS Simulator,name=iPhone 16:"
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination "platform=iOS Simulator,name=iPhone 16" build || echo "Вариант 2 не сработал"
        
        echo ""
        echo "3. platform=iOS Simulator,name=iPhone SE (3rd generation):"
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination "platform=iOS Simulator,name=iPhone SE (3rd generation)" build || echo "Вариант 3 не сработал"
        
        echo ""
        echo "4. БЕЗ destination (Xcode выберет сам):"
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN build || echo "Вариант 4 не сработал"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-final-correct-build
        path: mobile_apps/ALADDIN_iOS/build/
        retention-days: 7
