name: iOS Solution 2 - Create Simulator

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/**' ]

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: List available simulators
      run: |
        echo "=== ДОСТУПНЫЕ СИМУЛЯТОРЫ ДО СОЗДАНИЯ ==="
        xcrun simctl list devices available | grep iPhone || echo "iPhone симуляторы не найдены"
        echo ""
        echo "=== ДОСТУПНЫЕ ТИПЫ УСТРОЙСТВ ==="
        xcrun simctl list devicetypes | grep iPhone | head -5
        
    - name: Create iPhone 15 simulator
      id: create_simulator
      run: |
        echo "=== СОЗДАЕМ IPHONE 15 СИМУЛЯТОР ==="
        # Создаем новый симулятор
        SIMULATOR_ID=$(xcrun simctl create "iPhone 15 Test" "iPhone 15" "iOS-17-0" || echo "ERROR")
        
        if [ "$SIMULATOR_ID" = "ERROR" ]; then
          echo "❌ Не удалось создать симулятор с iOS-17-0"
          echo "Пробуем iOS-16-0..."
          SIMULATOR_ID=$(xcrun simctl create "iPhone 15 Test" "iPhone 15" "iOS-16-0" || echo "ERROR")
        fi
        
        if [ "$SIMULATOR_ID" = "ERROR" ]; then
          echo "❌ Не удалось создать симулятор с iOS-16-0"
          echo "Пробуем без указания версии..."
          SIMULATOR_ID=$(xcrun simctl create "iPhone 15 Test" "iPhone 15" || echo "ERROR")
        fi
        
        if [ "$SIMULATOR_ID" = "ERROR" ]; then
          echo "❌ Не удалось создать симулятор"
          echo "Используем generic destination"
          echo "simulator_id=generic" >> $GITHUB_OUTPUT
        else
          echo "✅ Создан симулятор: $SIMULATOR_ID"
          echo "simulator_id=$SIMULATOR_ID" >> $GITHUB_OUTPUT
        fi
        
    - name: Boot created simulator
      if: steps.create_simulator.outputs.simulator_id != 'generic'
      run: |
        echo "=== ЗАПУСКАЕМ СОЗДАННЫЙ СИМУЛЯТОР ==="
        xcrun simctl boot "${{ steps.create_simulator.outputs.simulator_id }}" || echo "Симулятор уже запущен"
        
    - name: Build iOS app
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "=== КОМПИЛИРУЕМ iOS ПРИЛОЖЕНИЕ ==="
        
        if [ "${{ steps.create_simulator.outputs.simulator_id }}" = "generic" ]; then
          echo "Используем generic destination"
          xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination 'platform=iOS Simulator' build
        else
          echo "Используем созданный симулятор: ${{ steps.create_simulator.outputs.simulator_id }}"
          xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination "platform=iOS Simulator,id=${{ steps.create_simulator.outputs.simulator_id }}" build
        fi
        
        echo "=== ПРОВЕРЯЕМ BUILD ПАПКУ ==="
        ls -la build/ || echo "build папка не найдена"
        echo ""
        echo "=== ИЩЕМ .app ФАЙЛЫ ==="
        find build/ -name "*.app" -type d || echo ".app файлы не найдены"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-build-solution2
        path: mobile_apps/ALADDIN_iOS/build/
        retention-days: 7
