name: iOS Test 4 - Asset Catalog Fix
on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/test4.txt' ]
  workflow_dispatch:

jobs:
  ios-test-4:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
    
    - name: iOS Test 4 - Asset Catalog Fix
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "🧪 ТЕСТ 4: ASSET CATALOG - ОТКЛЮЧИТЬ ПРОБЛЕМНЫЕ ASSETS"
        echo "======================================================"
        echo ""
        echo "🔍 ПРОБЛЕМА:"
        echo "❌ CompileAssetCatalogVariant thinned - ошибка runtime версии"
        echo "❌ Asset catalog требует совместимые runtime версии"
        echo ""
        echo "✅ РЕШЕНИЕ:"
        echo "Попробуем отключить проблемные asset операции"
        echo ""
        echo "🧪 ТЕСТ: Без asset catalog оптимизаций"
        if xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination "platform=iOS Simulator,name=iPhone 16 Pro" COMPILER_INDEX_STORE_ENABLE=NO build; then
          echo "✅ УСПЕХ! Без asset оптимизаций работает!"
          
          echo ""
          echo "📱 Результат сборки:"
          ls -la build/ || echo "build папка не найдена"
          echo ""
          echo "📱 Ищем .app файлы:"
          find build/ -name "*.app" -type d || echo ".app файлы не найдены"
          
          echo ""
          echo "🎉 РЕШЕНИЕ НАЙДЕНО!"
          echo "Используйте: COMPILER_INDEX_STORE_ENABLE=NO"
        else
          echo "❌ Без asset оптимизаций не работает"
          echo "Пробуем с отключенными warnings:"
          if xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination "platform=iOS Simulator,name=iPhone 16 Pro" GCC_WARN_INHIBIT_ALL_WARNINGS=YES build; then
            echo "✅ УСПЕХ! С отключенными warnings работает!"
            echo "Используйте: GCC_WARN_INHIBIT_ALL_WARNINGS=YES"
          else
            echo "❌ С отключенными warnings тоже не работает"
          fi
        fi
