name: iOS Solution 6 - Download Platform

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/trigger_solution6.txt' ]

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: Download iOS platform
      run: |
        echo "=== СКАЧИВАЕМ iOS ПЛАТФОРМУ ==="
        echo "Скачиваем iOS платформу..."
        
        # Пробуем скачать iOS SDK
        xcodebuild -downloadPlatform iOS || echo "Не удалось скачать iOS SDK"
        
        echo ""
        echo "=== ПРОВЕРЯЕМ РЕЗУЛЬТАТ УСТАНОВКИ ==="
        xcodebuild -showsdks | grep iOS || echo "iOS SDK все еще не найдены"
        
    - name: Install specific iOS versions
      run: |
        echo "=== УСТАНАВЛИВАЕМ КОНКРЕТНЫЕ ВЕРСИИ iOS ==="
        
        # Пробуем установить iOS 17.0
        echo "Пробуем установить iOS 17.0..."
        xcodebuild -downloadPlatform iOS -version 17.0 || echo "iOS 17.0 недоступна"
        
        # Пробуем установить iOS 16.0
        echo "Пробуем установить iOS 16.0..."
        xcodebuild -downloadPlatform iOS -version 16.0 || echo "iOS 16.0 недоступна"
        
        # Пробуем установить iOS 15.0
        echo "Пробуем установить iOS 15.0..."
        xcodebuild -downloadPlatform iOS -version 15.0 || echo "iOS 15.0 недоступна"
        
    - name: Build with downloaded platform
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "=== КОМПИЛИРУЕМ С СКАЧАННОЙ ПЛАТФОРМОЙ ==="
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-build-solution6
        path: mobile_apps/ALADDIN_iOS/build/
        retention-days: 7