name: iOS Test 5 - Debug Configuration

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/trigger_test5.txt' ]

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: Test 5 - Debug Configuration
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "=== ТЕСТ 5: -configuration Debug ==="
        echo "Компилируем с явным указанием Debug конфигурации"
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -configuration Debug build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-test5-debug
        path: mobile_apps/ALADDIN_iOS/build/
        retention-days: 7
