name: iOS Ultra Simple Build

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/**' ]

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: Build iOS app
      run: |
        cd mobile_apps/ALADDIN_iOS
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination 'platform=iOS' build
