name: iOS Version Test - Specific iOS Version

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/trigger_version.txt' ]

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: Check available iOS versions
      run: |
        echo "=== ПРОВЕРЯЕМ ДОСТУПНЫЕ ВЕРСИИ iOS ==="
        xcodebuild -showsdks | grep iOS
        
    - name: Version Test - Specific iOS Version
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "=== ТЕСТ С КОНКРЕТНОЙ ВЕРСИЕЙ iOS ==="
        echo "Пробуем разные версии iOS:"
        
        echo ""
        echo "1. iOS 17.0:"
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination "platform=iOS Simulator,OS=17.0" build || echo "iOS 17.0 не работает"
        
        echo ""
        echo "2. iOS 16.0:"
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination "platform=iOS Simulator,OS=16.0" build || echo "iOS 16.0 не работает"
        
        echo ""
        echo "3. iOS 15.0:"
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination "platform=iOS Simulator,OS=15.0" build || echo "iOS 15.0 не работает"
        
        echo ""
        echo "4. Без указания версии (Xcode выберет сам):"
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination "platform=iOS Simulator" build || echo "Без версии не работает"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-version-test
        path: mobile_apps/ALADDIN_iOS/build/
        retention-days: 7
