name: iOS Simple Test 2 - List Simulators

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/simple_test_2.txt' ]

jobs:
  list-simulators-test:
    runs-on: macos-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: Test 2 - List Simulators
      run: |
        echo "🧪 ТЕСТ 2: СПИСОК СИМУЛЯТОРОВ"
        echo "================================"
        echo "Проверяем доступные симуляторы..."
        
        echo "Версия Xcode:"
        xcodebuild -version
        
        echo ""
        echo "Доступные iPhone симуляторы:"
        xcrun simctl list devices available | grep "iPhone" || echo "iPhone симуляторы не найдены"
        
        echo ""
        echo "Все доступные устройства:"
        xcrun simctl list devices available | head -20
        
        echo ""
        echo "iOS SDK:"
        xcodebuild -showsdks | grep "iOS" || echo "iOS SDK не найдены"
        
        echo "✅ Тест 2 завершен успешно"
        
    - name: Upload Test 2 Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-simple-test-2
        path: .
        retention-days: 1
