name: iOS Find Available Simulators

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/find_simulators.txt' ]

jobs:
  find-simulators:
    runs-on: macos-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
      
    - name: Find Available Simulators
      run: |
        echo "🔍 ПОИСК ДОСТУПНЫХ СИМУЛЯТОРОВ"
        echo "================================"
        
        echo "1️⃣ ВСЕ ДОСТУПНЫЕ СИМУЛЯТОРЫ:"
        xcrun simctl list devices available
        
        echo ""
        echo "2️⃣ ТОЛЬКО IPHONE СИМУЛЯТОРЫ:"
        xcrun simctl list devices available | grep iPhone
        
        echo ""
        echo "3️⃣ ПОИСК IPHONE 15:"
        xcrun simctl list devices available | grep -i "iPhone 15" || echo "❌ iPhone 15 не найден"
        
        echo ""
        echo "4️⃣ ПОИСК IPHONE 14:"
        xcrun simctl list devices available | grep -i "iPhone 14" || echo "❌ iPhone 14 не найден"
        
        echo ""
        echo "5️⃣ ПОИСК IPHONE SE:"
        xcrun simctl list devices available | grep -i "iPhone SE" || echo "❌ iPhone SE не найден"
        
        echo ""
        echo "6️⃣ ВСЕ ДОСТУПНЫЕ iOS ВЕРСИИ:"
        xcrun simctl list runtimes
        
        echo ""
        echo "7️⃣ ПЕРВЫЕ 5 ДОСТУПНЫХ IPHONE:"
        xcrun simctl list devices available | grep iPhone | head -5
        
        echo ""
        echo "8️⃣ ПОПЫТКА С ПЕРВЫМ ДОСТУПНЫМ IPHONE:"
        FIRST_IPHONE=$(xcrun simctl list devices available | grep iPhone | head -1 | awk -F'[()]' '{print $2}' || echo "")
        if [ -n "$FIRST_IPHONE" ]; then
          echo "Найден iPhone: $FIRST_IPHONE"
          echo "FIRST_IPHONE_ID=$FIRST_IPHONE" >> $GITHUB_ENV
        else
          echo "❌ Ни одного iPhone симулятора не найдено"
        fi
        
    - name: Test with First Available iPhone
      if: env.FIRST_IPHONE_ID != ''
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "🧪 ТЕСТ С ПЕРВЫМ ДОСТУПНЫМ IPHONE:"
        echo "ID: $FIRST_IPHONE_ID"
        
        # Попробуем с ID
        if xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination "platform=iOS Simulator,id=$FIRST_IPHONE_ID" build; then
          echo "✅ УСПЕХ с ID: $FIRST_IPHONE_ID"
          ls -la build/
        else
          echo "❌ Не удалось с ID: $FIRST_IPHONE_ID"
        fi
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: simulator-search-results
        path: mobile_apps/ALADDIN_iOS/build/
        retention-days: 1
