name: iOS Correct Test - iOS Simulator

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/trigger_correct.txt' ]

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: Correct Test - iOS Simulator
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "=== ПРАВИЛЬНЫЙ ТЕСТ: platform=iOS Simulator ==="
        echo "Используем СИМУЛЯТОР (не реальное устройство)"
        echo "GitHub Actions имеет симуляторы, но НЕ имеет реальных iPhone"
        
        # Компилируем на симуляторе
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination "platform=iOS Simulator" build
        
        echo "=== ПРОВЕРЯЕМ BUILD ПАПКУ ==="
        ls -la build/ || echo "build папка не найдена"
        echo ""
        echo "=== ИЩЕМ .app ФАЙЛЫ ==="
        find build/ -name "*.app" -type d || echo ".app файлы не найдены"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-correct-simulator
        path: mobile_apps/ALADDIN_iOS/build/
        retention-days: 7
