name: iOS Simple Test 3 - Check Project

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/simple_test_3.txt' ]

jobs:
  check-project-test:
    runs-on: macos-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: Test 3 - Check Project
      run: |
        echo "🧪 ТЕСТ 3: ПРОВЕРКА ПРОЕКТА"
        echo "================================"
        
        cd mobile_apps/ALADDIN_iOS
        
        echo "Проверяем iOS проект..."
        echo "Рабочая директория: $(pwd)"
        echo "Список файлов:"
        ls -la
        
        echo ""
        echo "Проверяем .xcodeproj файл:"
        if [ -f "ALADDIN.xcodeproj/project.pbxproj" ]; then
          echo "✅ ALADDIN.xcodeproj найден"
          echo "Размер проекта: $(du -sh ALADDIN.xcodeproj)"
        else
          echo "❌ ALADDIN.xcodeproj не найден"
        fi
        
        echo ""
        echo "Проверяем схему:"
        xcodebuild -project ALADDIN.xcodeproj -list || echo "Не удалось получить список схем"
        
        echo ""
        echo "Проверяем build настройки:"
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -showBuildSettings | head -10 || echo "Не удалось получить настройки сборки"
        
        echo "✅ Тест 3 завершен успешно"
        
    - name: Upload Test 3 Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-simple-test-3
        path: mobile_apps/ALADDIN_iOS/
        retention-days: 1
