name: iOS Simple Test 8 - Verify .app File

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/simple_test_8.txt' ]

jobs:
  verify-app-test:
    runs-on: macos-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: Test 8 - Verify .app File
      run: |
        echo "🧪 ТЕСТ 8: ПРОВЕРКА .app ФАЙЛА"
        echo "================================"
        
        cd mobile_apps/ALADDIN_iOS
        
        echo "Сначала компилируем приложение:"
        
        # Очищаем предыдущие сборки
        rm -rf build/
        
        # Компилируем
        if xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -configuration Release -destination "platform=iOS Simulator,name=iPhone 15" build; then
          echo "✅ Компиляция успешна"
          
          echo ""
          echo "Проверяем .app файл:"
          
          # Ищем .app файлы
          APP_FILES=$(find build/ -name "*.app" -type d)
          
          if [ -n "$APP_FILES" ]; then
            echo "✅ .app файлы найдены:"
            echo "$APP_FILES"
            
            # Берем первый .app файл
            APP_FILE=$(echo "$APP_FILES" | head -1)
            
            echo ""
            echo "📱 АНАЛИЗ .app ФАЙЛА:"
            echo "Путь: $APP_FILE"
            echo "Размер: $(du -sh "$APP_FILE" | cut -f1)"
            
            echo ""
            echo "Содержимое .app файла:"
            ls -la "$APP_FILE"
            
            # Проверяем Info.plist
            if [ -f "$APP_FILE/Info.plist" ]; then
              echo ""
              echo "📄 Info.plist найден:"
              plutil -p "$APP_FILE/Info.plist" | head -15
            else
              echo ""
              echo "❌ Info.plist не найден"
            fi
            
            # Проверяем исполняемый файл
            EXECUTABLE=$(find "$APP_FILE" -name "ALADDIN" -type f | head -1)
            if [ -n "$EXECUTABLE" ]; then
              echo ""
              echo "✅ Исполняемый файл найден: $EXECUTABLE"
              echo "Размер исполняемого файла: $(du -sh "$EXECUTABLE" | cut -f1)"
            else
              echo ""
              echo "❌ Исполняемый файл не найден"
            fi
            
            echo ""
            echo "🎉 УСПЕХ! .app ФАЙЛ ГОТОВ ДЛЯ APP STORE!"
            
          else
            echo "❌ .app файлы не найдены"
            echo "Содержимое build папки:"
            find build/ -type f | head -10
          fi
          
        else
          echo "❌ Компиляция не удалась"
        fi
        
        echo "✅ Тест 8 завершен"
        
    - name: Upload Test 8 Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-simple-test-8
        path: mobile_apps/ALADDIN_iOS/build/
        retention-days: 1
