name: iOS Test 2 - SDK Version Fix
on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/test2.txt' ]
  workflow_dispatch:

jobs:
  ios-test-2:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
    
    - name: iOS Test 2 - SDK Version Fix
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "🧪 ТЕСТ 2: SDK ВЕРСИЯ - КОНКРЕТНАЯ SDK"
        echo "====================================="
        echo ""
        echo "🔍 ПРОБЛЕМА:"
        echo "❌ SDK 22A3362 не совместим с runtime [22E238, 22F77, 22G86, 23A343]"
        echo ""
        echo "✅ РЕШЕНИЕ:"
        echo "Используем конкретную SDK версию из доступных"
        echo ""
        echo "🔍 Доступные iOS SDK:"
        xcodebuild -showsdks | grep "iOS"
        echo ""
        echo "🧪 ТЕСТ: С конкретной SDK версией"
        # Попробуем с iphonesimulator SDK
        if xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -sdk iphonesimulator build; then
          echo "✅ УСПЕХ! SDK iphonesimulator работает!"
          
          echo ""
          echo "📱 Результат сборки:"
          ls -la build/ || echo "build папка не найдена"
          echo ""
          echo "📱 Ищем .app файлы:"
          find build/ -name "*.app" -type d || echo ".app файлы не найдены"
          
          echo ""
          echo "🎉 РЕШЕНИЕ НАЙДЕНО!"
          echo "Используйте: -sdk iphonesimulator"
        else
          echo "❌ SDK iphonesimulator не работает"
          echo "Проверяем доступные runtime:"
          xcrun simctl list runtimes | grep iOS | head -3
        fi
