name: iOS Solution 4 - No Destination

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/**' ]

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: Check project structure
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "=== ПРОВЕРЯЕМ СТРУКТУРУ ПРОЕКТА ==="
        ls -la
        echo ""
        echo "=== ПРОВЕРЯЕМ XCODE ПРОЕКТ ==="
        ls -la ALADDIN.xcodeproj/
        echo ""
        echo "=== ПРОВЕРЯЕМ SCHEMES ==="
        xcodebuild -list -project ALADDIN.xcodeproj
        
    - name: Build iOS app WITHOUT destination
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "=== КОМПИЛИРУЕМ iOS ПРИЛОЖЕНИЕ БЕЗ DESTINATION ==="
        echo "Используем только scheme, без указания destination"
        
        # Попробуем разные варианты компиляции
        echo "1. Попытка: xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN build"
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN build || echo "Попытка 1 не удалась"
        
        echo ""
        echo "2. Попытка: xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -configuration Debug build"
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -configuration Debug build || echo "Попытка 2 не удалась"
        
        echo ""
        echo "3. Попытка: xcodebuild -project ALADDIN.xcodeproj -target ALADDIN build"
        xcodebuild -project ALADDIN.xcodeproj -target ALADDIN build || echo "Попытка 3 не удалась"
        
        echo "=== ПРОВЕРЯЕМ BUILD ПАПКУ ==="
        ls -la build/ || echo "build папка не найдена"
        echo ""
        echo "=== ИЩЕМ .app ФАЙЛЫ ==="
        find build/ -name "*.app" -type d || echo ".app файлы не найдены"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-build-solution4
        path: mobile_apps/ALADDIN_iOS/build/
        retention-days: 7
