name: iOS iPhone 16 Pro Test

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/trigger_iphone16_pro.txt' ]

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: iPhone 16 Pro Test
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "=== ТЕСТ С iPhone 16 Pro ==="
        echo "Используем РЕАЛЬНО ДОСТУПНЫЙ симулятор iPhone 16 Pro"
        
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination "platform=iOS Simulator,name=iPhone 16 Pro" build
        
        echo "=== ПРОВЕРЯЕМ BUILD ПАПКУ ==="
        ls -la build/ || echo "build папка не найдена"
        echo ""
        echo "=== ИЩЕМ .app ФАЙЛЫ ==="
        find build/ -name "*.app" -type d || echo ".app файлы не найдены"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-iphone16-pro-build
        path: mobile_apps/ALADDIN_iOS/build/
        retention-days: 7
