name: iOS Runtime Fix - Get .app File
on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/fix_runtime.txt' ]
  workflow_dispatch:

jobs:
  fix-runtime-build:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
    
    - name: iOS Runtime Fix - All Problems Solved
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "🎯 ИСПРАВЛЯЕМ ВСЕ ПРОБЛЕМЫ:"
        echo "============================"
        echo "1. Runtime version compatibility"
        echo "2. Deployment target (11.0 -> 13.0)"
        echo "3. Asset Catalog bypass"
        echo "4. Specific device destination"
        echo ""
        
        echo "📱 Проверяем доступные runtime:"
        xcrun simctl list runtimes | grep iOS
        
        echo ""
        echo "🔧 РЕШЕНИЕ: Используем iPhone 16 Pro с правильными параметрами"
        
        # Исправляем все проблемы одним запросом
        if xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN \
          -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.4" \
          -sdk iphonesimulator \
          IPHONEOS_DEPLOYMENT_TARGET=13.0 \
          CODE_SIGNING_ALLOWED=NO \
          ASSETCATALOG_COMPILER_APPICON_NAME="" \
          ASSETCATALOG_COMPILER_ACCENT_COLOR_NAME="" \
          COMPILER_INDEX_STORE_ENABLE=NO \
          GCC_WARN_INHIBIT_ALL_WARNINGS=YES \
          build; then
          
          echo "✅ УСПЕХ! Все проблемы решены!"
          
          # Ищем созданный .app файл
          echo ""
          echo "📱 Поиск .app файла:"
          find . -name "*.app" -type d | head -5
          
          # Проверяем build папку
          echo ""
          echo "📂 Проверяем build папку:"
          if [ -d "build" ]; then
            ls -la build/
            find build/ -name "*.app" -type d || echo "Ищем в других местах..."
          fi
          
          # Проверяем DerivedData
          echo ""
          echo "📂 Проверяем DerivedData:"
          DERIVED_DATA=$(xcrun xcodebuild -showBuildSettings -project ALADDIN.xcodeproj -scheme ALADDIN 2>/dev/null | grep "BUILD_DIR" | head -1 | awk '{print $3}' || echo "")
          if [ -n "$DERIVED_DATA" ]; then
            echo "Build directory: $DERIVED_DATA"
            find "$DERIVED_DATA" -name "*.app" -type d 2>/dev/null | head -5 || echo "Не найдено в $DERIVED_DATA"
          fi
          
          # Пробуем найти в стандартных местах
          echo ""
          echo "📂 Стандартные места поиска:"
          find /Users/runner/Library/Developer/Xcode/DerivedData -name "ALADDIN.app" -type d 2>/dev/null | head -3 || echo "Не найдено в DerivedData"
          
          echo ""
          echo "🎉 РЕШЕНИЕ НАЙДЕНО!"
          echo "Используем: iPhone 16 Pro,OS=18.4 + DEPLOYMENT_TARGET=13.0"
          
        else
          echo "❌ Пробуем альтернативный подход..."
          
          # Альтернативный подход с другими runtime версиями
          for RUNTIME in "18.5" "18.6" "26.0"; do
            echo "🧪 Тестируем iOS $RUNTIME..."
            if xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN \
              -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=$RUNTIME" \
              IPHONEOS_DEPLOYMENT_TARGET=13.0 \
              CODE_SIGNING_ALLOWED=NO \
              ASSETCATALOG_COMPILER_APPICON_NAME="" \
              build; then
              echo "✅ УСПЕХ с iOS $RUNTIME!"
              find . -name "*.app" -type d | head -5
              exit 0
            fi
          done
          
          echo "❌ Все попытки провалились"
          exit 1
        fi
        
        echo ""
        echo "📱 ФИНАЛЬНАЯ ПРОВЕРКА .app ФАЙЛА:"
        find . -name "*.app" -type d | head -10 || echo "❌ .app файлы не найдены"
    
    - name: Find and Upload .app file
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "🔍 Поиск .app файла по всей системе..."
        
        # Поиск во всех возможных местах
        APP_PATHS=()
        
        # 1. Локальная build папка
        if [ -d "build" ]; then
          APP_PATHS+=("build"/*.app)
        fi
        
        # 2. DerivedData
        DERIVED_PATHS=$(find /Users/runner/Library/Developer/Xcode/DerivedData -name "ALADDIN.app" -type d 2>/dev/null || true)
        if [ -n "$DERIVED_PATHS" ]; then
          APP_PATHS+=($DERIVED_PATHS)
        fi
        
        # 3. Поиск по всему проекту
        PROJECT_APPS=$(find . -name "*.app" -type d 2>/dev/null || true)
        if [ -n "$PROJECT_APPS" ]; then
          APP_PATHS+=($PROJECT_APPS)
        fi
        
        # 4. Стандартные места Xcode
        STANDARD_APPS=$(find /Users/runner/Library/Developer/Xcode/DerivedData -path "*Debug-iphonesimulator*" -name "*.app" -type d 2>/dev/null | head -5 || true)
        if [ -n "$STANDARD_APPS" ]; then
          APP_PATHS+=($STANDARD_APPS)
        fi
        
        echo "Найдено путей: ${#APP_PATHS[@]}"
        for path in "${APP_PATHS[@]}"; do
          if [ -d "$path" ]; then
            echo "✅ Найден .app: $path"
            ls -la "$path"
            echo "📱 Размер: $(du -sh "$path" 2>/dev/null || echo "неизвестно")"
            echo "APP_PATH=$path" >> $GITHUB_ENV
            break
          fi
        done
        
        # Если ничего не найдено, создаем информацию для отладки
        if [ -z "$APP_PATH" ]; then
          echo "❌ .app файл не найден"
          echo "Отладочная информация:"
          find . -name "build" -type d 2>/dev/null | head -5
          ls -la /Users/runner/Library/Developer/Xcode/DerivedData/ 2>/dev/null || echo "DerivedData недоступен"
        fi
    
    - name: Upload .app file
      uses: actions/upload-artifact@v4
      if: env.APP_PATH != ''
      with:
        name: aladdin-ios-app-final
        path: ${{ env.APP_PATH }}
        if-no-files-found: warn
        retention-days: 30
    
    - name: Upload debug info
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-build-debug-info
        path: mobile_apps/ALADDIN_iOS/
        if-no-files-found: warn
        retention-days: 7
