name: iOS Test 8 - Scheme Validation

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/trigger_test8.txt' ]

jobs:
  test-8-scheme-validation:
    runs-on: macos-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: Test 8 - Validate ALADDIN Scheme
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "=== ТЕСТ 8: ВАЛИДАЦИЯ СХЕМЫ ALADDIN ==="
        
        # Проверяем схему
        echo "Доступные схемы:"
        xcodebuild -project ALADDIN.xcodeproj -list
        
        echo ""
        echo "Детали схемы ALADDIN:"
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -showBuildSettings | head -20
        
        echo ""
        echo "Тест только схемы без destination:"
        rm -rf build/
        
        if xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN build; then
          echo "✅ Схема ALADDIN работает"
          echo "Build папка:"
          ls -la build/
          echo "Ищем .app файлы:"
          find build/ -name "*.app" -type d
        else
          echo "❌ Схема ALADDIN не работает"
        fi
        
    - name: Upload Test 8 Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-test8-scheme-validation
        path: mobile_apps/ALADDIN_iOS/build/
        retention-days: 7
