name: iOS Minimal Build

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/**' ]

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: Build iOS app
      run: |
        cd mobile_apps/ALADDIN_iOS
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination 'platform=iOS Simulator' build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: ios-build
        path: mobile_apps/ALADDIN_iOS/build/Release-iphonesimulator/
