name: iOS Error 70 - Quick Fix

on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/trigger_error70_fix.txt' ]

jobs:
  fix-error70:
    runs-on: macos-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
        
    - name: Quick Fix - Error 70
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "🚨 БЫСТРОЕ ИСПРАВЛЕНИЕ ОШИБКИ 70"
        echo "ПРОБЛЕМА: platform=iOS ищет реальное устройство"
        echo "РЕШЕНИЕ: platform=iOS Simulator использует симулятор"
        
        # Очищаем предыдущие сборки
        rm -rf build/
        
        echo "=== СПИСОК ДОСТУПНЫХ СИМУЛЯТОРОВ ==="
        xcrun simctl list devices available | grep "iPhone" | head -5
        
        echo "=== КОМПИЛЯЦИЯ НА СИМУЛЯТОРЕ ==="
        # Используем симулятор iPhone 15 (всегда доступен в GitHub Actions)
        xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -destination "platform=iOS Simulator,name=iPhone 15" build
        
        echo "=== ПРОВЕРКА РЕЗУЛЬТАТА ==="
        echo "Build папка:"
        ls -la build/
        
        echo "Ищем .app файлы:"
        find build/ -name "*.app" -type d -exec echo "✅ Найден: {}" \;
        
        # Проверяем размер .app файла
        APP_FILE=$(find build/ -name "*.app" -type d | head -1)
        if [ -n "$APP_FILE" ]; then
          echo "📱 Размер .app файла:"
          du -sh "$APP_FILE"
          echo "📋 Содержимое .app файла:"
          ls -la "$APP_FILE"
        fi
        
    - name: Upload Fixed Build
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-error70-fixed
        path: mobile_apps/ALADDIN_iOS/build/
        retention-days: 7
