name: iOS Test 5 - Universal Solution
on:
  push:
    branches: [ main ]
    paths: [ 'mobile_apps/ALADDIN_iOS/test5.txt' ]
  workflow_dispatch:

jobs:
  ios-test-5:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0.0'
    
    - name: iOS Test 5 - Universal Solution
      run: |
        cd mobile_apps/ALADDIN_iOS
        echo "🧪 ТЕСТ 5: УНИВЕРСАЛЬНЫЙ - КОМБИНИРОВАННОЕ РЕШЕНИЕ"
        echo "=================================================="
        echo ""
        echo "🔍 ПРОБЛЕМА:"
        echo "❌ Runtime версии не совместимы"
        echo "❌ Deployment target слишком старый (11.0)"
        echo "❌ Asset catalog требует совместимые версии"
        echo ""
        echo "✅ РЕШЕНИЕ:"
        echo "Комбинируем все исправления:"
        echo "1. SDK iphonesimulator"
        echo "2. Deployment target 13.0"
        echo "3. Отключенные warnings"
        echo ""
        echo "🧪 ТЕСТ: Комбинированное решение"
        if xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 16 Pro" IPHONEOS_DEPLOYMENT_TARGET=13.0 GCC_WARN_INHIBIT_ALL_WARNINGS=YES COMPILER_INDEX_STORE_ENABLE=NO build; then
          echo "✅ УСПЕХ! Комбинированное решение работает!"
          
          echo ""
          echo "📱 Результат сборки:"
          ls -la build/ || echo "build папка не найдена"
          echo ""
          echo "📱 Ищем .app файлы:"
          find build/ -name "*.app" -type d || echo ".app файлы не найдены"
          
          echo ""
          echo "🎉 ФИНАЛЬНОЕ РЕШЕНИЕ НАЙДЕНО!"
          echo "Используйте:"
          echo "-sdk iphonesimulator"
          echo "IPHONEOS_DEPLOYMENT_TARGET=13.0"
          echo "GCC_WARN_INHIBIT_ALL_WARNINGS=YES"
          echo "COMPILER_INDEX_STORE_ENABLE=NO"
        else
          echo "❌ Комбинированное решение не работает"
          echo "Пробуем упрощенную версию:"
          if xcodebuild -project ALADDIN.xcodeproj -scheme ALADDIN -sdk iphonesimulator IPHONEOS_DEPLOYMENT_TARGET=13.0 build; then
            echo "✅ УСПЕХ! Упрощенная версия работает!"
            echo "Используйте: -sdk iphonesimulator IPHONEOS_DEPLOYMENT_TARGET=13.0"
          else
            echo "❌ Упрощенная версия тоже не работает"
            echo "Проверяем доступные runtime еще раз:"
            xcrun simctl list runtimes | grep iOS
          fi
        fi
